[[language]]
name = "nix"
auto-format = true
formatter = { command = "nixfmt" }

[[language]]
name = "go"
auto-format = true

[[language]]
name = "zig"
auto-format = true

[[language]]
name = "rust"
auto-format = false

[[language]]
name = "typst"
auto-format = true
