theme = "autumn_night_transparent"

[keys.normal]
h = "move_char_left"
t = "move_visual_line_down"
n = "move_visual_line_up"
s = "move_char_right"

[editor]
bufferline = "multiple"
rulers = [80]

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name"]
